### ISSUE TITLE
Checklist for end of Tiles^3 project

### ISSUE THREAD

**Issue by aroberge** [aroberge/reeborg#336]
- [ ] Create a world where single cycle animated images are drawn on every possible canvas and ensure that they disappear at the end
 - [ ] See if it is possible to turn this into a reliable functional test.
 - [ ] confirm automated jsdoc is complete
      * [ ] background_tile
      * [ ] bridge_layer
      * [ ] obstacles
      * [ ] decorative
      * [ ] goal
      * [ ] objects
      * [ ] robots
      * [ ] overlay
 - [ ] confirm hand-written jsdoc is complete
      * [ ] background_tile
      * [ ] bridge_layer
      * [ ] obstacles
      * [ ] decorative
      * [ ] goal
      * [ ] objects
      * [ ] robots
      * [ ] overlay
      * [ ] callbacks
      * [ ] transformations
      * [ ] OOP including composition
  - [ ] Review need for any translation; ideally, for each set of unit tests, ensure that the required translations are covered.
